version: "3"
services:
  db:
    container_name: db
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example123
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=mixiphp
      - MYSQL_PASSWORD=example123
    volumes:
      - "data:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - default
  server:
    container_name: mixiphp
    image: ldcmleo1360/mixiphp
    restart: always
    links:
      - db
    volumes:
      - "/YOUR/FOLDER/TO/mixiphp/public:/var/www/html"
      - "/YOUR/FOLDER/TO/mixiphp/core:/var/www/mixi/core"
      - "/YOUR/FOLDER/TO/mixiphp/app:/var/www/mixi/app"
      - "/YOUR/FOLDER/TO/mixiphp/config:/var/www/mixi/config"
      - "/YOUR/FOLDER/TO/mixiphp/routes:/var/www/mixi/routes"
    ports:
      - "80:80"
    networks:
      - default
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links: 
       - db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: mixiphp
      MYSQL_PASSWORD: example123
      MYSQL_ROOT_PASSWORD: example123 
volumes:
  data:
